version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: development
    container_name: phantom-mask-api
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    env_file:
      - .env
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
